[package]
name = "opnvote-common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
base64 = "0.22.1"
getrandom = "0.3.3"
ring = "0.17.14"