#!/usr/bin/env bash

#opnVote - Reliable, verifiable and secure electronic voting systems
#Copyright (C)  2025  Max Bossing <max@bossi.ng>
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as
#published by the Free Software Foundation, either version 3 of the
#License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Simple test of the ca certificate chain generated by generate_mtls_chain.sh
# Use in conjunction with mtls_server.sh

CERTS_PATH="../../resources/certs"

curl -v --cert "$CERTS_PATH/client.crt" --key "$CERTS_PATH/client.key" --cacert "$CERTS_PATH/client-full-chain.crt" https://localhost:8443